# Generated by Django 3.0.5 on 2020-04-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_homework', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_homework.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_homework.Subject')),
            ],
        ),
    ]
